export const exitWithError = () => process.exit(1);
